/// Constructs a context struct of mutable references from a state that
/// implements [`Lens`] for each field type in the context.
///
/// Implemented on the **context type** so that blanket impls generated by
/// `#[context]` satisfy Rust's orphan rules — the local context type is always
/// `Self`. The `State` parameter is left generic and constrained by `Lens`
/// bounds on each impl, so one context type composes with any state that has
/// the right fields.
///
/// In practice you should use the `#[context]` attribute macro rather than
/// writing `Compose` impls by hand — it generates both the `&'a mut` struct
/// and the `unsafe impl Compose` for you, and rejects duplicate field types at
/// compile time.
///
/// # Safety
///
/// Implementations must ensure every field in `Self` points to a distinct,
/// non-overlapping region of `state`. Returning the same field twice, or a
/// pointer to memory outside `state`, allows callers to create aliased `&mut`
/// references through otherwise safe code, which is immediate undefined
/// behaviour.
///
/// # Example
///
/// ```rust
/// use app::{Compose, Lens};
///
/// struct Renderer { frame: u32 }
/// struct Wayland  { committed: bool }
///
/// struct AppState { renderer: Renderer, wayland: Wayland }
///
/// unsafe impl Lens<Renderer> for AppState {
///     fn lens(&mut self) -> &mut Renderer { &mut self.renderer }
/// }
/// unsafe impl Lens<Wayland> for AppState {
///     fn lens(&mut self) -> &mut Wayland { &mut self.wayland }
/// }
///
/// struct RenderCtx<'a> {
///     renderer: &'a mut Renderer,
///     wayland:  &'a mut Wayland,
/// }
///
/// unsafe impl<'a, S> Compose<'a, S> for RenderCtx<'a>
/// where
///     S: Lens<Renderer> + Lens<Wayland> + 'a,
/// {
///     fn compose(state: &'a mut S) -> Self {
///         unsafe {
///             RenderCtx {
///                 renderer: &mut *(Lens::<Renderer>::lens(state) as *mut Renderer),
///                 wayland:  &mut *(Lens::<Wayland>::lens(state) as *mut Wayland),
///             }
///         }
///     }
/// }
///
/// let mut state = AppState { renderer: Renderer { frame: 0 }, wayland: Wayland { committed: false } };
/// let ctx = RenderCtx::compose(&mut state);
/// ctx.renderer.frame += 1;
/// ctx.wayland.committed = true;
/// ```
pub unsafe trait Compose<'a, State: 'a>: Sized {
    fn compose(state: &'a mut State) -> Self;
}
